### ISSUE TITLE
[Feature Request] Automatic Version selection

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#55] opened 2020-09-28 15:34 UTC
**Is your feature request related to a problem? Please describe.**
Its pretty annoying that I have to change my version when connecting to specific servers.

**Is this related specifically to ViaFabric?**
Yes. On the server it would make no sense.

**Describe the solution you'd like**
Would be cool, if viaversion would auto select the game version when connecting to a server. Maybe even a version Line at the server add-thing

**Describe alternatives you've considered**
I don't think there are any lol

**Which versions is this for?**
*

**Comment by creeper123123321** [comment] 2020-09-28 16:40
duplicate of #33

**Closed by creeper123123321** 2020-09-28 16:40 UTC
Labels: enhancement
