### ISSUE TITLE
Fabric API Incompatibility

### ISSUE THREAD

**Issue by Clumsiifi** [ViaVersion/ViaFabric#319] opened 2024-04-21 03:00 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/2535c9087b8ce7685075a5efc21c4cdb610a874855dbd6448fc380100f8fcdea

### Bug Description

When inserting Fabric API into the mods folder of a 1.20.4 Server, the client lower than 1.20.4 can't connect even if the server has latest Via Fabric, Viaversion, ViaBackwards and ViaRewind.

### Steps to Reproduce

1. Put the Fabric API Mod into the mods folder of the server
2. Join with a lower version.

### Expected Behavior

Player can join and experience Minecraft.

### Additional Server Info

fabric-server-mc.1.20.4-loader.0.15.10-launcher.1.0.1 and fabric-api-0.97.0+1.20.4

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment] 2024-04-21 09:40
Duplicate of [ViaBackwards' #642](https://github.com/ViaVersion/ViaBackwards/issues/642).

**Closed by Kichura** 2024-04-21 09:40 UTC
Labels: bug
