### ISSUE TITLE
Auto Version

### ISSUE THREAD

**Issue by UltraBlackLinux** [ViaVersion/ViaFabric#37] opened 2020-07-28 18:40 UTC
**Is your feature request related to a problem? Please describe.**
Would be cool if you wouldnt have to pick the mc version all time

**Describe the solution you'd like**
An option to autoselect the version
**Describe alternatives you've considered**
none

**Which versions is this for?**
all

**Comment by creeper123123321** [comment] 2020-07-28 20:54
Duplicate of  #33

**Closed by creeper123123321** 2020-07-28 20:54 UTC
