### ISSUE TITLE
1.16.5 server, 1.20.2 client: ERROR IN Protocol1_17To1_16_4 IN REMAP OF ENTITY_METADATA

### ISSUE THREAD

**Issue by FrostBird347** [ViaVersion/ViaFabric#278] opened 2023-11-05 12:36 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/896385be5db801b8f5fc69b26dabc53c9a17f7eb2229ccbb563707711b4da9fe

### Console Error

[trimmed log](https://mclo.gs/0dsl1H5)
[full log](https://github.com/ViaVersion/ViaFabric/files/13279065/latest.log)

### Bug Description

When a 1.20.2 client joins a 1.16.5 server, the error message `ERROR IN Protocol1_17To1_16_4 IN REMAP OF ENTITY_METADATA` is spammed in the logs and sometimes the player's connection times out while joining.

### Steps to Reproduce

1. Host a 1.16.5 fabric server with viafabric
2. Connect to the server with a 1.20.2 client
3. Observe the error in the server log

### Expected Behavior

This error should not occur while the player is joining.

### Additional Server Info

[Map used](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/maps/3166897-ctm-final-paradox-map-release-english-espanol-1)

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [ ] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment] 2023-11-07 08:14
This is likely caused by a bad third-party mod, Please perform a binary search to see what causes viafabric to complain about bad entity metadata packets being sent to server.

**Comment by FrostBird347** [comment] 2023-11-07 10:19
I still experience this issue after removing all mods except for viafabric and fabric api.

**Comment by Kichura** [comment] 2023-11-07 11:29
Can you test this on a clean world that has no data on it? if it still happens from there, you might have to update viafabric + viaversion jars to latest CI builds.

**Comment by FrostBird347** [comment] 2023-11-07 11:51
It does not occur on a clean world

**Comment by Kichura** [comment] 2023-11-07 12:28
Then something bad has been stored in the world save. *(possibly corrupt data or bad NBT items/blocks/etc is hidden somewhere)*

**Comment by Kichura** [comment] 2023-12-28 00:33
Closing this since this issue has turned out to be caused by bad world save after all, can be noticed by checking the bad achievements at beginning.

**Closed by Kichura** 2023-12-28 00:33 UTC
Labels: bug
