### ISSUE TITLE
1.8.8 block placing on feet

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaFabric#25] opened 2020-06-11 21:06 UTC
**Describe the bug, provide any errors**
Setup: 1.16-pre2 Fabric with ViaFabric installed. ([ViaFabric-Config](https://pastebin.com/Qb4rVZHX))
If you try to tower up on a paper 1.8 server with ViaFabric the block will place inside of the player resulting in getting pushed out and falling.

**How can we reproduce it?**
1. Select version 1.8 in ViaFabric and join a paper 1.8.8 server
2. Try to tower up
3. You will get pushed out

**Expected behaviour**
No blocks getting placed inside the player

**Screenshots**
https://gyazo.com/6e882b78ad48e863daa52d4c667adde2

**ViaVersion Dump:**
- Can't do that in ViaFabric. ([ViaFabric-Config](https://pastebin.com/Qb4rVZHX))

**Additional server info**
No plugins were present on the test-server.

**Comment by Username404-59** [comment] 2020-06-11 22:40
Aren't you getting pushed because you place sand blocks? I thought it was a normal minecraft mechanic ;-;

**Comment by RaphiMC** [comment] 2020-06-11 22:42
You arent supposed to be able to place them in the position you are standing

**Comment by Xernium** [comment] 2020-06-11 22:49
This happens on 1.8 paper servers. ViaVersion is supposed to have a fix for this but that fix can only work if it’s installed on the server. Can’t be fixed. Aka if it’s installed on the client with Fabric or on a bungeecord you *cannot* avoid this issue.

**Comment by RaphiMC** [comment] 2020-06-11 22:51
Theoretically it is possible to clientside check if the player would place a block inside of himself and cancel that packet.

**Comment by Xernium** [comment] 2020-06-11 22:52
Fair. Please move this issue to ViaFabric then as it requires tracking chunk data (not viable for proxy only use)

**Comment by Xernium** [comment] 2020-06-11 22:53
> Fair. Please move this issue to ViaFabric then as it requires tracking chunk data (not viable for proxy only use)

Never use the github app. (Doesn’t Show the current repo correctly). I’ll look into doing a fix for that.

**Comment by RaphiMC** [comment] 2020-06-11 22:54
It is already in viafabric and it doesnt necesarly require tracking of chunk data, it could be solved using a mixin

**Comment by creeper123123321** [comment] 2020-06-25 13:15
Related to ViaVersion#592

**Comment by creeper123123321** [comment] 2021-05-01 20:25
is it happening on latest alpha version?

**Comment by RaphiMC** [comment] 2021-05-01 20:34
I already kinda fixed it in my ViaVersion Pull Request (but only for 1.9-1.12.2 clients). 1.13+ requires some clientside modification to readd some checks that the clients before did.

**Comment by RaphiMC** [comment] 2021-05-01 20:34
Also what alpha version? of what?

**Comment by creeper123123321** [comment] 2021-05-30 18:06
Wontfix: this is caused by a missing check on server-side

**Closed by creeper123123321** 2021-05-30 18:06 UTC
Labels: bug, confirmed, low priority, wontfix
