### ISSUE TITLE
A way to change the position of the "VIA" button

### ISSUE THREAD

**Issue by The-Nyla** [ViaVersion/ViaFabric#179] opened 2022-04-20 15:11 UTC
**Is your feature request related to a problem? Please describe.**
sometimes buttons added by other mods cover the via button or visa versa

**Is this related specifically to ViaFabric?**
yes

**Describe the solution you'd like**
just an option in the via menu that lets you drag the via button to the position you want it to be at.

**Comment by creeper123123321** [comment] 2022-04-21 15:31
duplicate of #97

**Closed as completed by creeper123123321** 2022-04-21 15:31 UTC
Labels: duplicate
