### ISSUE TITLE
[1.21.1 -> 1.19.4] Packet Type: RESPAWN

### ISSUE THREAD

**Issue by tangjin0418** [ViaVersion/ViaFabric#375] opened 2024-09-22 03:51 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/81c2db91b1344eaa8c4db3cca26b629b68ebc3f1ecd8b5b6950e1a8bd6b127f6

### Console Error

https://mclo.gs/KzQvMG1

### Bug Description

Disconnect.

### Steps to Reproduce

1. Use 1.21.1
2. Set target to 1.19.4
3. Join a 1.19.4 server run after velocity (not sure, but I run the server behind velocity)

### Expected Behavior

No disconnect.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment] 2024-09-22 10:11
Does this persist on fabric too instead of just quilt?

**Comment by tangjin0418** [comment] 2024-09-28 07:32
Yes, the problem presist.
When I join server and do `/server s2`, I got disconnected.

https://mclo.gs/fFAMDkT

**Comment by tangjin0418** [comment] 2024-09-28 07:47
Now, I use `ViaFabricPlus`.
Seems the problem disappeared (at least not getting disconnected).

**Comment by Kichura** [comment] 2024-09-28 12:14
Can you try updating viafabric to latest build and also viaversion to latest CI build? if this fails too then it's either a bad server or third party mod causing it.

**Comment by tangjin0418** [comment] 2024-09-29 15:35
I think using `ViaFabricPlus` is fine.
If you are not going to investigate this, I think we can close this issue.

**Comment by Kichura** [comment] 2024-09-29 15:50
Closing this as i cannot reproduce it.

**Closed by Kichura** 2024-09-29 15:50 UTC
Labels: bug, question
