### ISSUE TITLE
Development build does not work.

### ISSUE THREAD

**Issue by mygizli04** [ViaVersion/ViaFabric#50] opened 2020-08-28 09:54 UTC
**Describe the bug, provide any errors**
There are a lot of errors in the logs, and the game does not open. Got build from [here](https://github.com/ViaVersion/ViaFabric/releases/tag/build-446.1). I have other mods installed here but it happens without them as well. Here are the [logs](https://gist.github.com/mygizli04/7955f3503144aca17f7f630099cb9b08)

**Expected behaviour**
Minecraft to open properly.

**Comment by creeper123123321** [comment] 2020-08-28 09:57
>viafabric@0.2.9-SNAPSHOT+build-435.1-mc-1.16

update it, and viabackwards 3.1.0 is only compatible with viaversion 3.1.0

**Comment by mygizli04** [comment] 2020-08-28 10:04
https://gist.github.com/mygizli04/d35b9d599bf534d8718f2e84cb827904

**Comment by creeper123123321** [comment] 2020-09-05 06:53
Does it still happen with latest ViaVersion/Backwards from CI?

**Comment by mygizli04** [comment] 2020-09-05 09:21
No, but it doesn't launch now, it's stuck trying to load mappings now.

https://gist.github.com/mygizli04/ba2af3665a04d4a8371e8d438a2be3ba

**Comment by creeper123123321** [comment] 2020-11-03 11:25
Does it still happen in 0.2.16?

**Comment by mygizli04** [comment] 2020-11-03 13:03
It still gets stuck, but in a ( i believe ) later stage. https://gist.github.com/mygizli04/10e4dc6f55901c58922ee051da5446fb

**Comment by creeper123123321** [comment] 2021-05-18 12:10
duplicate of #101 ?

**Closed by creeper123123321** 2021-05-18 12:10 UTC
Labels: bug, couldn't reproduce

**Comment by mygizli04** [comment] 2021-05-18 19:50
This issue is older than the one you linked, but yes it’s the same issue.
