### ISSUE TITLE
NPE caused by config

### ISSUE THREAD

**Issue by SulpherStaer** [ViaVersion/ViaFabric#176] opened 2022-03-29 16:38 UTC
**Describe the bug, provide any errors**
The server crashes on boot.
[gist crashlog](https://gist.github.com/SulpherStaer/09c62dcb9e90f49e7e2e11013d82c758)

**Is this happening specifically on ViaFabric?**
(Optional)
No idea - only use fabric

**How can we reproduce it?**
- Minecraft 1.18.2 with Fabric Loader 0.13.3
- viafabric-0.4.6+266-main OR viafabric-0.4.6+269-main
- ViaBackwards-4.2.1

**Expected behaviour**
- The server doesn't crash

**ViaVersion Dump**
- no dump available, server crashes.

**Additional server info**
- Is server using a proxy (eg. BungeeCord/Velocity)?
No proxy and mods are available in the gist.

I tried to use an older ticket https://github.com/ViaVersion/ViaFabric/issues/175 to alert that this issue is happening again, but I wasn't clear enough, so I opened a new ticket.

**Comment by Kichura** [comment] 2022-03-29 17:06
Duplicate of #175 - I put a comment on my own issue to give away the reasoning for this one.

**Comment by creeper123123321** [comment] 2022-03-29 22:48
this was caused by an invalid config

**Closed by creeper123123321** 2022-03-29 22:48 UTC
Labels: bug
