### ISSUE TITLE
[ViaVersion Client-Side] Crashes when pressing F3

### ISSUE THREAD

**Issue by jLn0n** [ViaVersion/ViaFabric#228] opened 2023-02-28 11:52 UTC
### `/viaversion dump` Output

non packet related, client sided only

### Console Error

[crash log](https://paste.gg/p/anonymous/ec471ea2d9e747c88685a19e994fb4d7)

### Bug Description

when pressing F3 while playing world, it just crashes

### Steps to Reproduce

1. play on a world/server
2. press F3

### Expected Behavior

it should not crash the client

### Additional Server Info

client crashes

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment] 2023-02-28 15:29
Duplicate of #224.

**Closed by Kichura** 2023-02-28 15:29 UTC
Labels: bug
