### ISSUE TITLE
1.14.4 Client on 1.8.8 server-side blockconnection errors

### ISSUE THREAD

**Issue by RaphiMC** [ViaVersion/ViaFabric#17] opened 2020-04-28 10:28 UTC
**Describe the bug, provide any errors**
Setup: 1.14.4 Fabric with ViaFabric installed. ([ViaFabric-Config](https://pastebin.com/Qb4rVZHX))
If serverside-blockconnections are enabled there are several bugs with explosions/ghost-blocks.

**How can we reproduce it?**
1. Enable serverside-blockconnections in the ViaFabric config
2. Select version 1.8 in ViaFabric and join a spigot 1.8.8 server
3. Place some tnt and ignite it
4. Some blocks will be only clientside (ghost-blocks)

**Expected behaviour**
I expect no ghost blocks. Expected behaviour can be seen by disabling serverside-blockconnections.

**Screenshots**
https://prnt.sc/s7aphg
Video showing the bug: https://streamable.com/o92vk0

**ViaVersion Dump:**
- Can't do that in ViaFabric. ([ViaFabric-Config](https://pastebin.com/Qb4rVZHX))

**Additional server info**
No plugins were present on the test-server.

**Comment by creeper123123321** [comment] 2020-04-28 10:35
Duplicate of ViaVersion/ViaVersion#1621

**Closed** 2020-04-28 10:35 UTC
