### ISSUE TITLE
DataFormatException with large system chat packets [1.20.4 -> 1.19.4]

### ISSUE THREAD

**Issue by Xenapte** [ViaVersion/ViaFabric#324] opened 2024-05-01 10:32 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/1b809d682ac2e7b51102c66a0fe2a124a43be563ecc606bf06843fd147894500

### Console Error

https://mclo.gs/aihPUyW

Yes, I know this is a bit long because it contains the entire data of that large packet.

### Bug Description

Some servers have plugins that allow arbitrary item to be displayed as a weapon in death messages. Killing players with an item that has a large NBT data size causes players running ViaFabric to disconnect with the DataFormatException.

### Steps to Reproduce

1. Set up a 1.19.4 server with plugins/mods that show any arbitrary item as weapon on death (e.g. PurpurMC with the config of `player-deaths-always-show-item: true`)
2. Log in on a 1.20.4 client with ViaFabric installed
3. Fill a shulker box with around 80 KB of data using books (my logs contain the NBT data of the exact shulker box that was used to generate the exception) - don't make it too long or nothing about its data will be sent to the client.
4. Use the shulker box to kill some player.

### Expected Behavior

The death message is displayed correctly with the shulker box as the weapon item.

### Additional Server Info

![](https://github.com/ViaVersion/ViaFabric/assets/17661805/fe3da7dd-5c58-4ee4-8cca-e7d54fdeb372)

Kick screen.

### Checklist

- [X] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [x] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by kreivon** [comment] 2024-05-01 20:53
Running into the same issue with ViaFabricPlus.

**Comment by Kichura** [comment] 2024-05-01 22:20
Closing this issue as OP has outdated ViaVersion, if you can reproduce this with latest viafabric + viaversion jars combined then make a reply and it will be reopened.

**Comment by Xenapte** [comment] 2024-05-02 02:31
Can confirm this still exists with the latest viafabric-0.4.14+68-main. In fact, trying to paste the command to summon that huge NBT data item into a command block causes a kick too, for the server sends the full command as feedback.

New viaversion dump: https://dump.viaversion.com/1b809d682ac2e7b51102c66a0fe2a124a43be563ecc606bf06843fd147894500
(I'll update the link in the issue report itself too)

Command used to summon the item: https://mclo.gs/pAvfoZk

**Comment by FlorianMichael** [comment] 2024-05-28 18:46
Same as https://github.com/ViaVersion/ViaVersion/blob/2d41eb52a6692e7552242091d749c3058d99f9e9/common/src/main/java/com/viaversion/viaversion/util/ComponentUtil.java#L78, seems to be down to ViaNBT not handling something Vanilla does

**Comment by FlorianMichael** [comment] 2024-05-29 11:35
Fixed with https://github.com/ViaVersion/ViaVersion/commit/af393c564f20f40f14d276e8e209bd625a6c24d8

**Closed by FlorianMichael** 2024-05-29 11:35 UTC
Labels: bug
