### ISSUE TITLE
Error decoding something

### ISSUE THREAD

**Issue by RealKomander** [ViaVersion/ViaFabric#282] opened 2023-11-25 10:31 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/074e2c827c8ae7ecc69388050960575bd76bcb9b72c0245ab9b115b690a29a28

### Console Error

[13:23:21] [Server thread/INFO]: com.mojang.authlib.GameProfile@5c3c95d[id=b18a2b65-0131-4c4f-926c-f81305475690,name=RealKomander,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcwMDkwNzc5NDc2OSwKICAicHJvZmlsZUlkIiA6ICJiMThhMmI2NTAxMzE0YzRmOTI2Y2Y4MTMwNTQ3NTY5MCIsCiAgInByb2ZpbGVOYW1lIiA6ICJSZWFsS29tYW5kZXIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWVhYzA0YzUxYjMyMDMxODliMTkxOTc5ZjMyZTg0NDJlZmQ4MzhhYWVlNDM4ZDZiNGU5NWJhYTYxOGFmYzNlYyIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0=, signature=tKYSuFlpyJPkgMzMcHN0Vf8LcR4DxLJtkQckFCKc4LWf+HoOfkvCYUIPvRxIR8fWij4da+6dBarm16z2ICs4vNR4Jg7xbBQaZ6qEFMF9+Hdz2aK8TbluEKUY6uZin6/9YLu9rhPWkm+N01W+h2yNJVSZFxbFRo/LGzl3N5GxZw/VtT4AdpqamkrGDKXjjNWQ8tgSK+omFSv/rqOdscKPH9UrYiy0/EdW/3At9j1bHfJnMIgI90X2f/ACBP3mTEyMdvBvH59ArxEKbe4xvJPhOCd8RgrFcwBjA35hTzCNb7oegbqyxJvokOwmKZoNe1ayOI2kDoSjWiGMgCqMmVauJwIDvsjEAOzl7ZDaFxId3cUnNrui2RzrhU8mIBVzxj9IsDPN1dhkaZGb4dYRSwDaDrTVWXikYi94kYk3bkOFDEcsIV8zGTcGPv6RKDIDWb9rso6P+IqHHJtO3oLKQy5Pj9TZpvnyazt/VDxCXX+EgWKLdU5f5P9yQL5QTa1Ve+nDsoQYH+Ky5CHEpvLfyA32L4o6iUXJuFlPAZa0Cr07WBO91dGuv2cjWXXA3cn3mSuQarcpHpQCDLGMxb/QRGnx1rAf/Y+nYxgftW7bdGoCRbewSFQ6IlMhqzOVtlX//IU0LqEXMQcquwQF7wlSK+Gd08dj6zNSSC8rI8wFZ+yZPSM=]]}] lost connection: Disconnected

### Bug Description

When I try to connect to my fabric 1.20.2 server through 1.20.1 client, I get this error in velocity console:

[13:23:21 ERROR]: [connected player] RealKomander (/IP): unable to connect to server classic
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.LoginPluginMessage Direction CLIENTBOUND Protocol 1.20 State LOGIN ID 4
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.netty.handler.codec.CorruptedFrameException: Bad string size (got 465914, maximum is 65536)
        at com.velocitypowered.proxy.protocol.util.NettyPreconditions.checkFrame(NettyPreconditions.java:83) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:200) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:192) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.ProtocolUtils.readString(ProtocolUtils.java:179) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.packet.LoginPluginMessage.decode(LoginPluginMessage.java:67) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[velocity-3.2.0-SNAPSHOT-290.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        ... 30 more

And even weirder error in the server console, that I showed above

Everything is fine if I try connectiong from 1.20.2 client, so it might be viafabric issue. However, it doesn't occur without fabric proxy lite, so I reported it to them as well

### Steps to Reproduce

1) Install viafabric, viabackwards and fabric proxy lite on 1.20.2 server
2) connect the server to velocity
3) try to connect to it from 1.20.1 client or lower

### Expected Behavior

Joining the server

### Checklist

- [ ] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by RealKomander** [comment] 2023-11-25 10:34
I know it could also be velocity's fault, I will open issue there if needed

**Comment by RealKomander** [comment] 2023-11-25 10:36
Maybe it's one of the alternitives of #275

**Comment by Kichura** [comment] 2023-11-25 11:38
Duplicate of #275.

**Closed by Kichura** 2023-11-25 11:38 UTC
Labels: bug
