### ISSUE TITLE
Disable swim and 1.5block sneak <1.13 protocol to prevent server false banned

### ISSUE THREAD

**Issue by xmxmxmmmm** [ViaVersion/ViaFabric#159] opened 2021-10-19 14:40 UTC
**Is your feature request related to a problem? Please describe.**
anticheats flagged and then false banned

**Is this related specifically to ViaFabric?**
yes, im using viafabric client mod to play older version server[mostly 1.8.x]

**Describe the solution you'd like**
disable swim and 1.5block sneak <1.13 protocol

**Describe alternatives you've considered**
X

**Which versions is this for?**
snapshot21w41a

**Comment by Kichura** [comment] 2021-10-19 15:00
> 
> 
> > This is most likely out of scope for ViaFabric. You should consider trying multiconnect instead as its built with clientside usage in mind and thus has both of the things you mentioned fixed.
> 
> Multiconnect does not support latest snapshot :( [Im lazy to switch clients]

As for that, currently confirmed as there hasn't been an update since september afraik; but you can file an issue to earthcomputer's repository to try and help you out with it - otherwise there's little we can do to back this up.

**Comment by FlorianMichael** [comment] 2023-11-10 21:10
Out of scope for ViaFabric, use https://github.com/ViaVersion/ViaFabricPlus

**Closed by FlorianMichael** 2023-11-10 21:10 UTC
Labels: enhancement, low priority
