### ISSUE TITLE
Mineplex keeps timing out on ViaFabric 1.8

### ISSUE THREAD

**Issue by Obscure2020** [ViaVersion/ViaFabric#160] opened 2021-11-07 18:30 UTC
**Describe the bug, provide any errors**
- [Mineplex](https://www.mineplex.com/) has for a long time supported all Minecraft versions from 1.8 onwards. However, although they claim all versions are "compatible," I have experienced several bugs and glitches over the last several years when attempting to play on Mineplex on any version newer than 1.8. In the past, I would keep a separate 1.8 instance of Minecraft to connect to old-compatible servers like Mineplex, but when I discovered ViaFabric, I realized that this could be a useful alternative. At least, if it worked properly.\
\
I started trying to use client-side ViaFabric to join Mineplex via version 1.8, but I keep experiencing random Timeouts for no reason. It's a real shame, since ViaFabric 1.8 does appear to be making things work (or at least _look_) better than 1.17. If I join Mineplex in 1.17, I see this:\
![2021-11-07_12 56 13](https://user-images.githubusercontent.com/69320464/140656611-ff20bac0-60a8-49dc-87fb-0c91e9e4d8ca.png)
If instead I use ViaFabric to join via 1.8, I see this:
![2021-11-07_12 56 42](https://user-images.githubusercontent.com/69320464/140656640-d77e64d4-288c-46a1-8ce9-91a61f019ffd.png)
But unfortunately, ViaFabric always turns into this:
![Screenshot 2021-11-07 125922](https://user-images.githubusercontent.com/69320464/140656674-6ed0e555-c0a8-4c93-af08-c5db2370b29e.png)

**How can we reproduce it?**
1. Install ViaFabric into your 1.17 Fabric client.
1. Activate Client-Side mode.
1. Add Mineplex to your server list using the IP `us.mineplex.com._v1_8.viafabric`.
1. Join the server.
1. Run around the hub for a few minutes. Eventually you'll get a timeout for no reason.

**Expected behaviour**
- The server should just remain connected. DUH.\
I'm really confused as to why this is happening. The connection doesn't even seem to slow down or lag or freeze or anything. The game just randomly times me out while running smoothly.

**Additional server info**
- Mineplex uses BungeeCord to achieve its cross-version compatibility. I'm trying to bypass that compatibility by using ViaFabric to join as a 1.8 player.

**Comment by Kichura** [comment] 2021-11-07 18:42
Can reproduce on this unit and it seems to affect ALL compatibility modes; even europe mineplex is broken by this workaround.

**Comment by Obscure2020** [comment] 2021-11-07 19:32
Thanks for confirming it's not just me.

**Comment by Camotoy** [comment] 2021-12-02 03:11
This should be re-tested - Mineplex is now basing their version support off of ViaVersion. Direct link from their Discord: https://discord.com/channels/381618442710679552/399370515627900938/915662342459629659

**Comment by Kichura** [comment] 2021-12-02 15:26
> This should be re-tested - Mineplex is now basing their version support off of ViaVersion. Direct link from their Discord: https://discord.com/channels/381618442710679552/399370515627900938/915662342459629659
> 
> Text copy:
> 
> > Hello all! I'm back once again to announce the first deployment of something long anticipated here on Mineplex @java - a totally new version support system! For quite some time now, versions above 1.8 haven't had the greatest experience playing Mineplex games with friends, and this has always been a big concern for us. A little while ago, the development team began working on improvements to the version support system, and we came to the conclusion that it would be better to entirely remove and replace our old multiversion support, rather than trying to patch all the issues in it. When we initially rolled the old system, it was only ever intended to temporarily bridge the gap between 1.8 and 1.9, and the variety of new versions that have since been released by Mojang have demanded a much more robust system. For this reason, over the past few months the development team has systematically removed every trace of the old version support and replaced it with a new system, built on a customized version of the popular plugin ViaVersion, which was rolled out to the public last night. While we're excited about this new system, we expect some minor visual issues to impact different Minecraft versions, and so would greatly appreciate your feedback in letting us know when you come across these issues. We'd love for you to head on over to the forums and make a bug report - just make sure to let us know what version you're playing on!
> 
> > We wish you a great start to the Holiday Season, and as always - Happy Mineplexing!

Cannot reproduce issue anymore as it seems to be fixed now.

**Closed** 2022-04-08 12:52 UTC
Labels: bug
