### ISSUE TITLE
Possible incompatibly with the Essentials mod on 1.20

### ISSUE THREAD

**Issue by GrimPlayzs** [ViaVersion/ViaFabric#255] opened 2023-06-08 17:12 UTC
### `/viaversion dump` Output

https://dump.viaversion.com/94f8b92235c27a183ac23fde953d066ae34cf186d0af1183e2d3bd59d062454e

### Bug Description

Game crashes upon going to the server list with the Essentials mod on 1.20. This did not occur on 1.19.4

### Steps to Reproduce

Install both the Essentials mod and ViaFabric on 1.20
Launch the game and go to the server list.
Observe the crash.

### Expected Behavior

The game should not crash with both mods working as intended.

Also, the crash log indicates it could be a GUI issue as both mods modify the server list screen with more buttons. I could be wrong though.

### Checklist

- [x] I have checked if this is specific to ViaFabric platform, and doesn't happen when running it on other platforms (Paper/Sponge/Velocity/Waterfall).
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Kichura** [comment] 2023-06-20 22:04
Please verify if this issue is also present on fabric itself and not just quilt.

**Comment by lynrayy** [comment] 2023-06-24 14:55
Essentials is bad mod

**Comment by Johni0702** [comment] 2023-08-17 09:44
This is caused by ViaFabric [`Redirect`ing a method call](https://github.com/ViaVersion/ViaFabric/blob/df04490b5db0709003792b85c2f6366dc5d8e6a6/viafabric-mc120/src/main/java/com/viaversion/fabric/mc120/mixin/gui/client/MixinServerEntry.java#L27-L35) of which Essential tries to `ModifyArg` one of the arguments.
In general `Redirect` should be avoided because it's inherently incompatible with other mods. In this case, it seems trivial to replace with a `ModifyArg` (which not only allows different mods to modify different arguments of the same call, but even composes well when multiple mods target the exact same argument).

**Comment by FlorianMichael** [comment] 2023-11-10 21:13
Fixed in https://github.com/ViaVersion/ViaFabric/commit/43b89472d34b84ade88af1c05e8008d8c916e4b9#diff-a0694a602635b9f3b46c233e4f6726346d3207b9dacf85737354f826b213b8a7

**Closed by FlorianMichael** 2023-11-10 21:13 UTC
Labels: bug
